<?php
/**
 * ConditionsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MRD API
 *
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiMrdSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Mydex\ApiMrdSdk\ApiException;
use Mydex\ApiMrdSdk\Configuration;
use Mydex\ApiMrdSdk\FormDataProcessor;
use Mydex\ApiMrdSdk\HeaderSelector;
use Mydex\ApiMrdSdk\ObjectSerializer;

/**
 * ConditionsApi Class Doc Comment
 *
 * @category Class
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConditionsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getConditionLevelOne' => [
            'application/json',
        ],
        'getConditionLevelThree' => [
            'application/json',
        ],
        'getConditionLevelTwo' => [
            'application/json',
        ],
        'getConditionRoutes' => [
            'application/json',
        ],
        'searchConditions' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getConditionLevelOne
     *
     * Retrieve a first-level Conditions page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelOne'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiMrdSdk\Model\ConditionResponse|\Mydex\ApiMrdSdk\Model\ConditionErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse
     */
    public function getConditionLevelOne($x_mrd_scopes, $param1, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelOne'][0])
    {
        list($response) = $this->getConditionLevelOneWithHttpInfo($x_mrd_scopes, $param1, $no_html, $nhs_links, $contentType);
        return $response;
    }

    /**
     * Operation getConditionLevelOneWithHttpInfo
     *
     * Retrieve a first-level Conditions page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelOne'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiMrdSdk\Model\ConditionResponse|\Mydex\ApiMrdSdk\Model\ConditionErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getConditionLevelOneWithHttpInfo($x_mrd_scopes, $param1, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelOne'][0])
    {
        $request = $this->getConditionLevelOneRequest($x_mrd_scopes, $param1, $no_html, $nhs_links, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\ConditionResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\ConditionErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiMrdSdk\Model\ConditionResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\ConditionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\ConditionErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getConditionLevelOneAsync
     *
     * Retrieve a first-level Conditions page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelOne'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConditionLevelOneAsync($x_mrd_scopes, $param1, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelOne'][0])
    {
        return $this->getConditionLevelOneAsyncWithHttpInfo($x_mrd_scopes, $param1, $no_html, $nhs_links, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getConditionLevelOneAsyncWithHttpInfo
     *
     * Retrieve a first-level Conditions page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelOne'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConditionLevelOneAsyncWithHttpInfo($x_mrd_scopes, $param1, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelOne'][0])
    {
        $returnType = '\Mydex\ApiMrdSdk\Model\ConditionResponse';
        $request = $this->getConditionLevelOneRequest($x_mrd_scopes, $param1, $no_html, $nhs_links, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getConditionLevelOne'
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelOne'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getConditionLevelOneRequest($x_mrd_scopes, $param1, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelOne'][0])
    {

        // verify the required parameter 'x_mrd_scopes' is set
        if ($x_mrd_scopes === null || (is_array($x_mrd_scopes) && count($x_mrd_scopes) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_mrd_scopes when calling getConditionLevelOne'
            );
        }

        // verify the required parameter 'param1' is set
        if ($param1 === null || (is_array($param1) && count($param1) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $param1 when calling getConditionLevelOne'
            );
        }
        if (strlen($param1) < 1) {
            throw new \InvalidArgumentException('invalid length for "$param1" when calling ConditionsApi.getConditionLevelOne, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/conditions/{param1}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $no_html,
            'no_html', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $nhs_links,
            'nhs_links', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_mrd_scopes !== null) {
            $headerParams['X-Mrd-Scopes'] = ObjectSerializer::toHeaderValue($x_mrd_scopes);
        }

        // path params
        if ($param1 !== null) {
            $resourcePath = str_replace(
                '{param1}',
                ObjectSerializer::toPathValue($param1),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getConditionLevelThree
     *
     * Retrieve a third-level Conditions page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string $param2 Second Conditions route segment. (required)
     * @param  string $param3 Third Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelThree'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiMrdSdk\Model\ConditionResponse|\Mydex\ApiMrdSdk\Model\ConditionErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse
     */
    public function getConditionLevelThree($x_mrd_scopes, $param1, $param2, $param3, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelThree'][0])
    {
        list($response) = $this->getConditionLevelThreeWithHttpInfo($x_mrd_scopes, $param1, $param2, $param3, $no_html, $nhs_links, $contentType);
        return $response;
    }

    /**
     * Operation getConditionLevelThreeWithHttpInfo
     *
     * Retrieve a third-level Conditions page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string $param2 Second Conditions route segment. (required)
     * @param  string $param3 Third Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelThree'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiMrdSdk\Model\ConditionResponse|\Mydex\ApiMrdSdk\Model\ConditionErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getConditionLevelThreeWithHttpInfo($x_mrd_scopes, $param1, $param2, $param3, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelThree'][0])
    {
        $request = $this->getConditionLevelThreeRequest($x_mrd_scopes, $param1, $param2, $param3, $no_html, $nhs_links, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\ConditionResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\ConditionErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiMrdSdk\Model\ConditionResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\ConditionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\ConditionErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getConditionLevelThreeAsync
     *
     * Retrieve a third-level Conditions page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string $param2 Second Conditions route segment. (required)
     * @param  string $param3 Third Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelThree'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConditionLevelThreeAsync($x_mrd_scopes, $param1, $param2, $param3, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelThree'][0])
    {
        return $this->getConditionLevelThreeAsyncWithHttpInfo($x_mrd_scopes, $param1, $param2, $param3, $no_html, $nhs_links, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getConditionLevelThreeAsyncWithHttpInfo
     *
     * Retrieve a third-level Conditions page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string $param2 Second Conditions route segment. (required)
     * @param  string $param3 Third Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelThree'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConditionLevelThreeAsyncWithHttpInfo($x_mrd_scopes, $param1, $param2, $param3, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelThree'][0])
    {
        $returnType = '\Mydex\ApiMrdSdk\Model\ConditionResponse';
        $request = $this->getConditionLevelThreeRequest($x_mrd_scopes, $param1, $param2, $param3, $no_html, $nhs_links, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getConditionLevelThree'
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string $param2 Second Conditions route segment. (required)
     * @param  string $param3 Third Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelThree'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getConditionLevelThreeRequest($x_mrd_scopes, $param1, $param2, $param3, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelThree'][0])
    {

        // verify the required parameter 'x_mrd_scopes' is set
        if ($x_mrd_scopes === null || (is_array($x_mrd_scopes) && count($x_mrd_scopes) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_mrd_scopes when calling getConditionLevelThree'
            );
        }

        // verify the required parameter 'param1' is set
        if ($param1 === null || (is_array($param1) && count($param1) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $param1 when calling getConditionLevelThree'
            );
        }
        if (strlen($param1) < 1) {
            throw new \InvalidArgumentException('invalid length for "$param1" when calling ConditionsApi.getConditionLevelThree, must be bigger than or equal to 1.');
        }
        
        // verify the required parameter 'param2' is set
        if ($param2 === null || (is_array($param2) && count($param2) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $param2 when calling getConditionLevelThree'
            );
        }
        if (strlen($param2) < 1) {
            throw new \InvalidArgumentException('invalid length for "$param2" when calling ConditionsApi.getConditionLevelThree, must be bigger than or equal to 1.');
        }
        
        // verify the required parameter 'param3' is set
        if ($param3 === null || (is_array($param3) && count($param3) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $param3 when calling getConditionLevelThree'
            );
        }
        if (strlen($param3) < 1) {
            throw new \InvalidArgumentException('invalid length for "$param3" when calling ConditionsApi.getConditionLevelThree, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/conditions/{param1}/{param2}/{param3}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $no_html,
            'no_html', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $nhs_links,
            'nhs_links', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_mrd_scopes !== null) {
            $headerParams['X-Mrd-Scopes'] = ObjectSerializer::toHeaderValue($x_mrd_scopes);
        }

        // path params
        if ($param1 !== null) {
            $resourcePath = str_replace(
                '{param1}',
                ObjectSerializer::toPathValue($param1),
                $resourcePath
            );
        }
        // path params
        if ($param2 !== null) {
            $resourcePath = str_replace(
                '{param2}',
                ObjectSerializer::toPathValue($param2),
                $resourcePath
            );
        }
        // path params
        if ($param3 !== null) {
            $resourcePath = str_replace(
                '{param3}',
                ObjectSerializer::toPathValue($param3),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getConditionLevelTwo
     *
     * Retrieve a second-level Conditions page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string $param2 Second Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelTwo'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiMrdSdk\Model\ConditionResponse|\Mydex\ApiMrdSdk\Model\ConditionErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse
     */
    public function getConditionLevelTwo($x_mrd_scopes, $param1, $param2, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelTwo'][0])
    {
        list($response) = $this->getConditionLevelTwoWithHttpInfo($x_mrd_scopes, $param1, $param2, $no_html, $nhs_links, $contentType);
        return $response;
    }

    /**
     * Operation getConditionLevelTwoWithHttpInfo
     *
     * Retrieve a second-level Conditions page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string $param2 Second Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelTwo'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiMrdSdk\Model\ConditionResponse|\Mydex\ApiMrdSdk\Model\ConditionErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getConditionLevelTwoWithHttpInfo($x_mrd_scopes, $param1, $param2, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelTwo'][0])
    {
        $request = $this->getConditionLevelTwoRequest($x_mrd_scopes, $param1, $param2, $no_html, $nhs_links, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\ConditionResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\ConditionErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiMrdSdk\Model\ConditionResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\ConditionResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\ConditionErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getConditionLevelTwoAsync
     *
     * Retrieve a second-level Conditions page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string $param2 Second Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelTwo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConditionLevelTwoAsync($x_mrd_scopes, $param1, $param2, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelTwo'][0])
    {
        return $this->getConditionLevelTwoAsyncWithHttpInfo($x_mrd_scopes, $param1, $param2, $no_html, $nhs_links, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getConditionLevelTwoAsyncWithHttpInfo
     *
     * Retrieve a second-level Conditions page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string $param2 Second Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelTwo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConditionLevelTwoAsyncWithHttpInfo($x_mrd_scopes, $param1, $param2, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelTwo'][0])
    {
        $returnType = '\Mydex\ApiMrdSdk\Model\ConditionResponse';
        $request = $this->getConditionLevelTwoRequest($x_mrd_scopes, $param1, $param2, $no_html, $nhs_links, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getConditionLevelTwo'
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $param1 First Conditions route segment. (required)
     * @param  string $param2 Second Conditions route segment. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionLevelTwo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getConditionLevelTwoRequest($x_mrd_scopes, $param1, $param2, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getConditionLevelTwo'][0])
    {

        // verify the required parameter 'x_mrd_scopes' is set
        if ($x_mrd_scopes === null || (is_array($x_mrd_scopes) && count($x_mrd_scopes) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_mrd_scopes when calling getConditionLevelTwo'
            );
        }

        // verify the required parameter 'param1' is set
        if ($param1 === null || (is_array($param1) && count($param1) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $param1 when calling getConditionLevelTwo'
            );
        }
        if (strlen($param1) < 1) {
            throw new \InvalidArgumentException('invalid length for "$param1" when calling ConditionsApi.getConditionLevelTwo, must be bigger than or equal to 1.');
        }
        
        // verify the required parameter 'param2' is set
        if ($param2 === null || (is_array($param2) && count($param2) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $param2 when calling getConditionLevelTwo'
            );
        }
        if (strlen($param2) < 1) {
            throw new \InvalidArgumentException('invalid length for "$param2" when calling ConditionsApi.getConditionLevelTwo, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/conditions/{param1}/{param2}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $no_html,
            'no_html', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $nhs_links,
            'nhs_links', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_mrd_scopes !== null) {
            $headerParams['X-Mrd-Scopes'] = ObjectSerializer::toHeaderValue($x_mrd_scopes);
        }

        // path params
        if ($param1 !== null) {
            $resourcePath = str_replace(
                '{param1}',
                ObjectSerializer::toPathValue($param1),
                $resourcePath
            );
        }
        // path params
        if ($param2 !== null) {
            $resourcePath = str_replace(
                '{param2}',
                ObjectSerializer::toPathValue($param2),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getConditionRoutes
     *
     * Retrieve available Conditions routes
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionRoutes'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiMrdSdk\Model\ConditionsRouteListResponse|\Mydex\ApiMrdSdk\Model\ConditionErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse
     */
    public function getConditionRoutes($x_mrd_scopes, string $contentType = self::contentTypes['getConditionRoutes'][0])
    {
        list($response) = $this->getConditionRoutesWithHttpInfo($x_mrd_scopes, $contentType);
        return $response;
    }

    /**
     * Operation getConditionRoutesWithHttpInfo
     *
     * Retrieve available Conditions routes
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionRoutes'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiMrdSdk\Model\ConditionsRouteListResponse|\Mydex\ApiMrdSdk\Model\ConditionErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getConditionRoutesWithHttpInfo($x_mrd_scopes, string $contentType = self::contentTypes['getConditionRoutes'][0])
    {
        $request = $this->getConditionRoutesRequest($x_mrd_scopes, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\ConditionsRouteListResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\ConditionErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiMrdSdk\Model\ConditionsRouteListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\ConditionsRouteListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\ConditionErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getConditionRoutesAsync
     *
     * Retrieve available Conditions routes
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionRoutes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConditionRoutesAsync($x_mrd_scopes, string $contentType = self::contentTypes['getConditionRoutes'][0])
    {
        return $this->getConditionRoutesAsyncWithHttpInfo($x_mrd_scopes, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getConditionRoutesAsyncWithHttpInfo
     *
     * Retrieve available Conditions routes
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionRoutes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getConditionRoutesAsyncWithHttpInfo($x_mrd_scopes, string $contentType = self::contentTypes['getConditionRoutes'][0])
    {
        $returnType = '\Mydex\ApiMrdSdk\Model\ConditionsRouteListResponse';
        $request = $this->getConditionRoutesRequest($x_mrd_scopes, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getConditionRoutes'
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getConditionRoutes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getConditionRoutesRequest($x_mrd_scopes, string $contentType = self::contentTypes['getConditionRoutes'][0])
    {

        // verify the required parameter 'x_mrd_scopes' is set
        if ($x_mrd_scopes === null || (is_array($x_mrd_scopes) && count($x_mrd_scopes) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_mrd_scopes when calling getConditionRoutes'
            );
        }


        $resourcePath = '/conditions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_mrd_scopes !== null) {
            $headerParams['X-Mrd-Scopes'] = ObjectSerializer::toHeaderValue($x_mrd_scopes);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchConditions
     *
     * Search Conditions content
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  \Mydex\ApiMrdSdk\Model\ConditionSearchFilter[] $filters Structured Conditions search filters supplied using indexed bracket notation, for example filters[0][operator]&#x3D;LIKE&amp;filters[0][value]&#x3D;cancer&amp;filters[0][condition]&#x3D;AND&amp;filters[1][operator]&#x3D;LIKE&amp;filters[1][value]&#x3D;treatment&amp;filters[1][condition]&#x3D;. Each filter must contain exactly value, operator and condition. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $search_all Extends Conditions search to page-content text and expander content in addition to the default page description. When supplied, this parameter must be set to &#39;true&#39;. This parameter is only valid on the search endpoint. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchConditions'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiMrdSdk\Model\ConditionsSearchResponse|\Mydex\ApiMrdSdk\Model\ConditionErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse
     */
    public function searchConditions($x_mrd_scopes, $filters, $no_html = null, $nhs_links = null, $search_all = null, string $contentType = self::contentTypes['searchConditions'][0])
    {
        list($response) = $this->searchConditionsWithHttpInfo($x_mrd_scopes, $filters, $no_html, $nhs_links, $search_all, $contentType);
        return $response;
    }

    /**
     * Operation searchConditionsWithHttpInfo
     *
     * Search Conditions content
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  \Mydex\ApiMrdSdk\Model\ConditionSearchFilter[] $filters Structured Conditions search filters supplied using indexed bracket notation, for example filters[0][operator]&#x3D;LIKE&amp;filters[0][value]&#x3D;cancer&amp;filters[0][condition]&#x3D;AND&amp;filters[1][operator]&#x3D;LIKE&amp;filters[1][value]&#x3D;treatment&amp;filters[1][condition]&#x3D;. Each filter must contain exactly value, operator and condition. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $search_all Extends Conditions search to page-content text and expander content in addition to the default page description. When supplied, this parameter must be set to &#39;true&#39;. This parameter is only valid on the search endpoint. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchConditions'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiMrdSdk\Model\ConditionsSearchResponse|\Mydex\ApiMrdSdk\Model\ConditionErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchConditionsWithHttpInfo($x_mrd_scopes, $filters, $no_html = null, $nhs_links = null, $search_all = null, string $contentType = self::contentTypes['searchConditions'][0])
    {
        $request = $this->searchConditionsRequest($x_mrd_scopes, $filters, $no_html, $nhs_links, $search_all, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\ConditionsSearchResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\ConditionErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiMrdSdk\Model\ConditionsSearchResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\ConditionsSearchResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\ConditionErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation searchConditionsAsync
     *
     * Search Conditions content
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  \Mydex\ApiMrdSdk\Model\ConditionSearchFilter[] $filters Structured Conditions search filters supplied using indexed bracket notation, for example filters[0][operator]&#x3D;LIKE&amp;filters[0][value]&#x3D;cancer&amp;filters[0][condition]&#x3D;AND&amp;filters[1][operator]&#x3D;LIKE&amp;filters[1][value]&#x3D;treatment&amp;filters[1][condition]&#x3D;. Each filter must contain exactly value, operator and condition. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $search_all Extends Conditions search to page-content text and expander content in addition to the default page description. When supplied, this parameter must be set to &#39;true&#39;. This parameter is only valid on the search endpoint. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchConditions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchConditionsAsync($x_mrd_scopes, $filters, $no_html = null, $nhs_links = null, $search_all = null, string $contentType = self::contentTypes['searchConditions'][0])
    {
        return $this->searchConditionsAsyncWithHttpInfo($x_mrd_scopes, $filters, $no_html, $nhs_links, $search_all, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchConditionsAsyncWithHttpInfo
     *
     * Search Conditions content
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  \Mydex\ApiMrdSdk\Model\ConditionSearchFilter[] $filters Structured Conditions search filters supplied using indexed bracket notation, for example filters[0][operator]&#x3D;LIKE&amp;filters[0][value]&#x3D;cancer&amp;filters[0][condition]&#x3D;AND&amp;filters[1][operator]&#x3D;LIKE&amp;filters[1][value]&#x3D;treatment&amp;filters[1][condition]&#x3D;. Each filter must contain exactly value, operator and condition. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $search_all Extends Conditions search to page-content text and expander content in addition to the default page description. When supplied, this parameter must be set to &#39;true&#39;. This parameter is only valid on the search endpoint. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchConditions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchConditionsAsyncWithHttpInfo($x_mrd_scopes, $filters, $no_html = null, $nhs_links = null, $search_all = null, string $contentType = self::contentTypes['searchConditions'][0])
    {
        $returnType = '\Mydex\ApiMrdSdk\Model\ConditionsSearchResponse';
        $request = $this->searchConditionsRequest($x_mrd_scopes, $filters, $no_html, $nhs_links, $search_all, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchConditions'
     *
     * @param  string $x_mrd_scopes MRD service scope required for Conditions endpoints. (required)
     * @param  \Mydex\ApiMrdSdk\Model\ConditionSearchFilter[] $filters Structured Conditions search filters supplied using indexed bracket notation, for example filters[0][operator]&#x3D;LIKE&amp;filters[0][value]&#x3D;cancer&amp;filters[0][condition]&#x3D;AND&amp;filters[1][operator]&#x3D;LIKE&amp;filters[1][value]&#x3D;treatment&amp;filters[1][condition]&#x3D;. Each filter must contain exactly value, operator and condition. (required)
     * @param  string|null $no_html Removes HTML markup from returned content. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $nhs_links Replaces eligible MRD URLs with their NHS website equivalents. When supplied, this parameter must be set to &#39;true&#39;. (optional)
     * @param  string|null $search_all Extends Conditions search to page-content text and expander content in addition to the default page description. When supplied, this parameter must be set to &#39;true&#39;. This parameter is only valid on the search endpoint. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchConditions'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchConditionsRequest($x_mrd_scopes, $filters, $no_html = null, $nhs_links = null, $search_all = null, string $contentType = self::contentTypes['searchConditions'][0])
    {

        // verify the required parameter 'x_mrd_scopes' is set
        if ($x_mrd_scopes === null || (is_array($x_mrd_scopes) && count($x_mrd_scopes) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_mrd_scopes when calling searchConditions'
            );
        }

        // verify the required parameter 'filters' is set
        if ($filters === null || (is_array($filters) && count($filters) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $filters when calling searchConditions'
            );
        }
        if (count($filters) < 1) {
            throw new \InvalidArgumentException('invalid value for "$filters" when calling ConditionsApi.searchConditions, number of items must be greater than or equal to 1.');
        }
        




        $resourcePath = '/conditions/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filters,
            'filters', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $no_html,
            'no_html', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $nhs_links,
            'nhs_links', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search_all,
            'search_all', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_mrd_scopes !== null) {
            $headerParams['X-Mrd-Scopes'] = ObjectSerializer::toHeaderValue($x_mrd_scopes);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
