<?php
/**
 * MedicinesApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MRD API
 *
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiMrdSdk\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Mydex\ApiMrdSdk\ApiException;
use Mydex\ApiMrdSdk\Configuration;
use Mydex\ApiMrdSdk\FormDataProcessor;
use Mydex\ApiMrdSdk\HeaderSelector;
use Mydex\ApiMrdSdk\ObjectSerializer;

/**
 * MedicinesApi Class Doc Comment
 *
 * @category Class
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MedicinesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getMedicineLevelOne' => [
            'application/json',
        ],
        'getMedicineLevelThree' => [
            'application/json',
        ],
        'getMedicineLevelTwo' => [
            'application/json',
        ],
        'getMedicinesRoutes' => [
            'application/json',
        ],
        'searchMedicines' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getMedicineLevelOne
     *
     * Retrieve a Medicine page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelOne'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response|\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse
     */
    public function getMedicineLevelOne($x_mrd_scopes, $param1, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelOne'][0])
    {
        list($response) = $this->getMedicineLevelOneWithHttpInfo($x_mrd_scopes, $param1, $no_html, $nhs_links, $contentType);
        return $response;
    }

    /**
     * Operation getMedicineLevelOneWithHttpInfo
     *
     * Retrieve a Medicine page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelOne'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response|\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMedicineLevelOneWithHttpInfo($x_mrd_scopes, $param1, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelOne'][0])
    {
        $request = $this->getMedicineLevelOneRequest($x_mrd_scopes, $param1, $no_html, $nhs_links, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getMedicineLevelOneAsync
     *
     * Retrieve a Medicine page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelOne'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMedicineLevelOneAsync($x_mrd_scopes, $param1, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelOne'][0])
    {
        return $this->getMedicineLevelOneAsyncWithHttpInfo($x_mrd_scopes, $param1, $no_html, $nhs_links, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMedicineLevelOneAsyncWithHttpInfo
     *
     * Retrieve a Medicine page
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelOne'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMedicineLevelOneAsyncWithHttpInfo($x_mrd_scopes, $param1, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelOne'][0])
    {
        $returnType = '\Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response';
        $request = $this->getMedicineLevelOneRequest($x_mrd_scopes, $param1, $no_html, $nhs_links, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMedicineLevelOne'
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelOne'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMedicineLevelOneRequest($x_mrd_scopes, $param1, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelOne'][0])
    {

        // verify the required parameter 'x_mrd_scopes' is set
        if ($x_mrd_scopes === null || (is_array($x_mrd_scopes) && count($x_mrd_scopes) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_mrd_scopes when calling getMedicineLevelOne'
            );
        }

        // verify the required parameter 'param1' is set
        if ($param1 === null || (is_array($param1) && count($param1) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $param1 when calling getMedicineLevelOne'
            );
        }
        if (strlen($param1) < 1) {
            throw new \InvalidArgumentException('invalid length for "$param1" when calling MedicinesApi.getMedicineLevelOne, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/medicines/{param1}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $no_html,
            'no_html', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $nhs_links,
            'nhs_links', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_mrd_scopes !== null) {
            $headerParams['X-Mrd-Scopes'] = ObjectSerializer::toHeaderValue($x_mrd_scopes);
        }

        // path params
        if ($param1 !== null) {
            $resourcePath = str_replace(
                '{param1}',
                ObjectSerializer::toPathValue($param1),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMedicineLevelThree
     *
     * Retrieve a page within a nested Medicine
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string $param2 Second Medicines route segment, normally identifying a medicine page or a medicine within a broader medicine family. (required)
     * @param  string $param3 Third Medicines route segment identifying a page within a nested medicine, such as common questions, dosage, side effects or interactions. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelThree'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response|\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse
     */
    public function getMedicineLevelThree($x_mrd_scopes, $param1, $param2, $param3, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelThree'][0])
    {
        list($response) = $this->getMedicineLevelThreeWithHttpInfo($x_mrd_scopes, $param1, $param2, $param3, $no_html, $nhs_links, $contentType);
        return $response;
    }

    /**
     * Operation getMedicineLevelThreeWithHttpInfo
     *
     * Retrieve a page within a nested Medicine
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string $param2 Second Medicines route segment, normally identifying a medicine page or a medicine within a broader medicine family. (required)
     * @param  string $param3 Third Medicines route segment identifying a page within a nested medicine, such as common questions, dosage, side effects or interactions. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelThree'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response|\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMedicineLevelThreeWithHttpInfo($x_mrd_scopes, $param1, $param2, $param3, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelThree'][0])
    {
        $request = $this->getMedicineLevelThreeRequest($x_mrd_scopes, $param1, $param2, $param3, $no_html, $nhs_links, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getMedicineLevelThreeAsync
     *
     * Retrieve a page within a nested Medicine
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string $param2 Second Medicines route segment, normally identifying a medicine page or a medicine within a broader medicine family. (required)
     * @param  string $param3 Third Medicines route segment identifying a page within a nested medicine, such as common questions, dosage, side effects or interactions. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelThree'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMedicineLevelThreeAsync($x_mrd_scopes, $param1, $param2, $param3, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelThree'][0])
    {
        return $this->getMedicineLevelThreeAsyncWithHttpInfo($x_mrd_scopes, $param1, $param2, $param3, $no_html, $nhs_links, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMedicineLevelThreeAsyncWithHttpInfo
     *
     * Retrieve a page within a nested Medicine
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string $param2 Second Medicines route segment, normally identifying a medicine page or a medicine within a broader medicine family. (required)
     * @param  string $param3 Third Medicines route segment identifying a page within a nested medicine, such as common questions, dosage, side effects or interactions. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelThree'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMedicineLevelThreeAsyncWithHttpInfo($x_mrd_scopes, $param1, $param2, $param3, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelThree'][0])
    {
        $returnType = '\Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response';
        $request = $this->getMedicineLevelThreeRequest($x_mrd_scopes, $param1, $param2, $param3, $no_html, $nhs_links, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMedicineLevelThree'
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string $param2 Second Medicines route segment, normally identifying a medicine page or a medicine within a broader medicine family. (required)
     * @param  string $param3 Third Medicines route segment identifying a page within a nested medicine, such as common questions, dosage, side effects or interactions. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelThree'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMedicineLevelThreeRequest($x_mrd_scopes, $param1, $param2, $param3, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelThree'][0])
    {

        // verify the required parameter 'x_mrd_scopes' is set
        if ($x_mrd_scopes === null || (is_array($x_mrd_scopes) && count($x_mrd_scopes) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_mrd_scopes when calling getMedicineLevelThree'
            );
        }

        // verify the required parameter 'param1' is set
        if ($param1 === null || (is_array($param1) && count($param1) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $param1 when calling getMedicineLevelThree'
            );
        }
        if (strlen($param1) < 1) {
            throw new \InvalidArgumentException('invalid length for "$param1" when calling MedicinesApi.getMedicineLevelThree, must be bigger than or equal to 1.');
        }
        
        // verify the required parameter 'param2' is set
        if ($param2 === null || (is_array($param2) && count($param2) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $param2 when calling getMedicineLevelThree'
            );
        }
        if (strlen($param2) < 1) {
            throw new \InvalidArgumentException('invalid length for "$param2" when calling MedicinesApi.getMedicineLevelThree, must be bigger than or equal to 1.');
        }
        
        // verify the required parameter 'param3' is set
        if ($param3 === null || (is_array($param3) && count($param3) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $param3 when calling getMedicineLevelThree'
            );
        }
        if (strlen($param3) < 1) {
            throw new \InvalidArgumentException('invalid length for "$param3" when calling MedicinesApi.getMedicineLevelThree, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/medicines/{param1}/{param2}/{param3}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $no_html,
            'no_html', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $nhs_links,
            'nhs_links', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_mrd_scopes !== null) {
            $headerParams['X-Mrd-Scopes'] = ObjectSerializer::toHeaderValue($x_mrd_scopes);
        }

        // path params
        if ($param1 !== null) {
            $resourcePath = str_replace(
                '{param1}',
                ObjectSerializer::toPathValue($param1),
                $resourcePath
            );
        }
        // path params
        if ($param2 !== null) {
            $resourcePath = str_replace(
                '{param2}',
                ObjectSerializer::toPathValue($param2),
                $resourcePath
            );
        }
        // path params
        if ($param3 !== null) {
            $resourcePath = str_replace(
                '{param3}',
                ObjectSerializer::toPathValue($param3),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMedicineLevelTwo
     *
     * Retrieve a Medicine subpage or nested medicine
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string $param2 Second Medicines route segment, normally identifying a medicine page or a medicine within a broader medicine family. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelTwo'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response|\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse
     */
    public function getMedicineLevelTwo($x_mrd_scopes, $param1, $param2, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelTwo'][0])
    {
        list($response) = $this->getMedicineLevelTwoWithHttpInfo($x_mrd_scopes, $param1, $param2, $no_html, $nhs_links, $contentType);
        return $response;
    }

    /**
     * Operation getMedicineLevelTwoWithHttpInfo
     *
     * Retrieve a Medicine subpage or nested medicine
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string $param2 Second Medicines route segment, normally identifying a medicine page or a medicine within a broader medicine family. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelTwo'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response|\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMedicineLevelTwoWithHttpInfo($x_mrd_scopes, $param1, $param2, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelTwo'][0])
    {
        $request = $this->getMedicineLevelTwoRequest($x_mrd_scopes, $param1, $param2, $no_html, $nhs_links, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getMedicineLevelTwoAsync
     *
     * Retrieve a Medicine subpage or nested medicine
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string $param2 Second Medicines route segment, normally identifying a medicine page or a medicine within a broader medicine family. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelTwo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMedicineLevelTwoAsync($x_mrd_scopes, $param1, $param2, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelTwo'][0])
    {
        return $this->getMedicineLevelTwoAsyncWithHttpInfo($x_mrd_scopes, $param1, $param2, $no_html, $nhs_links, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMedicineLevelTwoAsyncWithHttpInfo
     *
     * Retrieve a Medicine subpage or nested medicine
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string $param2 Second Medicines route segment, normally identifying a medicine page or a medicine within a broader medicine family. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelTwo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMedicineLevelTwoAsyncWithHttpInfo($x_mrd_scopes, $param1, $param2, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelTwo'][0])
    {
        $returnType = '\Mydex\ApiMrdSdk\Model\GetMedicineLevelOne200Response';
        $request = $this->getMedicineLevelTwoRequest($x_mrd_scopes, $param1, $param2, $no_html, $nhs_links, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMedicineLevelTwo'
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $param1 First Medicines route segment, normally identifying a medicine, medicine category or medicine family. (required)
     * @param  string $param2 Second Medicines route segment, normally identifying a medicine page or a medicine within a broader medicine family. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicineLevelTwo'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMedicineLevelTwoRequest($x_mrd_scopes, $param1, $param2, $no_html = null, $nhs_links = null, string $contentType = self::contentTypes['getMedicineLevelTwo'][0])
    {

        // verify the required parameter 'x_mrd_scopes' is set
        if ($x_mrd_scopes === null || (is_array($x_mrd_scopes) && count($x_mrd_scopes) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_mrd_scopes when calling getMedicineLevelTwo'
            );
        }

        // verify the required parameter 'param1' is set
        if ($param1 === null || (is_array($param1) && count($param1) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $param1 when calling getMedicineLevelTwo'
            );
        }
        if (strlen($param1) < 1) {
            throw new \InvalidArgumentException('invalid length for "$param1" when calling MedicinesApi.getMedicineLevelTwo, must be bigger than or equal to 1.');
        }
        
        // verify the required parameter 'param2' is set
        if ($param2 === null || (is_array($param2) && count($param2) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $param2 when calling getMedicineLevelTwo'
            );
        }
        if (strlen($param2) < 1) {
            throw new \InvalidArgumentException('invalid length for "$param2" when calling MedicinesApi.getMedicineLevelTwo, must be bigger than or equal to 1.');
        }
        



        $resourcePath = '/medicines/{param1}/{param2}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $no_html,
            'no_html', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $nhs_links,
            'nhs_links', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_mrd_scopes !== null) {
            $headerParams['X-Mrd-Scopes'] = ObjectSerializer::toHeaderValue($x_mrd_scopes);
        }

        // path params
        if ($param1 !== null) {
            $resourcePath = str_replace(
                '{param1}',
                ObjectSerializer::toPathValue($param1),
                $resourcePath
            );
        }
        // path params
        if ($param2 !== null) {
            $resourcePath = str_replace(
                '{param2}',
                ObjectSerializer::toPathValue($param2),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMedicinesRoutes
     *
     * Retrieve available Medicines routes
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicinesRoutes'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiMrdSdk\Model\MedicinesRoutesResponse|\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse
     */
    public function getMedicinesRoutes($x_mrd_scopes, string $contentType = self::contentTypes['getMedicinesRoutes'][0])
    {
        list($response) = $this->getMedicinesRoutesWithHttpInfo($x_mrd_scopes, $contentType);
        return $response;
    }

    /**
     * Operation getMedicinesRoutesWithHttpInfo
     *
     * Retrieve available Medicines routes
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicinesRoutes'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiMrdSdk\Model\MedicinesRoutesResponse|\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMedicinesRoutesWithHttpInfo($x_mrd_scopes, string $contentType = self::contentTypes['getMedicinesRoutes'][0])
    {
        $request = $this->getMedicinesRoutesRequest($x_mrd_scopes, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\MedicinesRoutesResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiMrdSdk\Model\MedicinesRoutesResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\MedicinesRoutesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getMedicinesRoutesAsync
     *
     * Retrieve available Medicines routes
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicinesRoutes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMedicinesRoutesAsync($x_mrd_scopes, string $contentType = self::contentTypes['getMedicinesRoutes'][0])
    {
        return $this->getMedicinesRoutesAsyncWithHttpInfo($x_mrd_scopes, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMedicinesRoutesAsyncWithHttpInfo
     *
     * Retrieve available Medicines routes
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicinesRoutes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMedicinesRoutesAsyncWithHttpInfo($x_mrd_scopes, string $contentType = self::contentTypes['getMedicinesRoutes'][0])
    {
        $returnType = '\Mydex\ApiMrdSdk\Model\MedicinesRoutesResponse';
        $request = $this->getMedicinesRoutesRequest($x_mrd_scopes, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMedicinesRoutes'
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMedicinesRoutes'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMedicinesRoutesRequest($x_mrd_scopes, string $contentType = self::contentTypes['getMedicinesRoutes'][0])
    {

        // verify the required parameter 'x_mrd_scopes' is set
        if ($x_mrd_scopes === null || (is_array($x_mrd_scopes) && count($x_mrd_scopes) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_mrd_scopes when calling getMedicinesRoutes'
            );
        }


        $resourcePath = '/medicines';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // header params
        if ($x_mrd_scopes !== null) {
            $headerParams['X-Mrd-Scopes'] = ObjectSerializer::toHeaderValue($x_mrd_scopes);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation searchMedicines
     *
     * Search Medicines content
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  \Mydex\ApiMrdSdk\Model\MedicinesSearchFilter[] $filters Structured Medicines search filters supplied using indexed bracket notation, for example filters[0][operator]&#x3D;LIKE&amp;filters[0][value]&#x3D;rapid acting insulin&amp;filters[0][condition]&#x3D;AND&amp;filters[1][operator]&#x3D;LIKE&amp;filters[1][value]&#x3D;diabetes&amp;filters[1][condition]&#x3D;. Each filter must contain exactly value, operator and condition. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string|null $search_all When supplied, the search also checks additional Medicines page content in addition to medicine descriptions. The only accepted value is &#39;true&#39;. This parameter is only valid on the search endpoint. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMedicines'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Mydex\ApiMrdSdk\Model\MedicineData[]|\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse
     */
    public function searchMedicines($x_mrd_scopes, $filters, $no_html = null, $nhs_links = null, $search_all = null, string $contentType = self::contentTypes['searchMedicines'][0])
    {
        list($response) = $this->searchMedicinesWithHttpInfo($x_mrd_scopes, $filters, $no_html, $nhs_links, $search_all, $contentType);
        return $response;
    }

    /**
     * Operation searchMedicinesWithHttpInfo
     *
     * Search Medicines content
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  \Mydex\ApiMrdSdk\Model\MedicinesSearchFilter[] $filters Structured Medicines search filters supplied using indexed bracket notation, for example filters[0][operator]&#x3D;LIKE&amp;filters[0][value]&#x3D;rapid acting insulin&amp;filters[0][condition]&#x3D;AND&amp;filters[1][operator]&#x3D;LIKE&amp;filters[1][value]&#x3D;diabetes&amp;filters[1][condition]&#x3D;. Each filter must contain exactly value, operator and condition. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string|null $search_all When supplied, the search also checks additional Medicines page content in addition to medicine descriptions. The only accepted value is &#39;true&#39;. This parameter is only valid on the search endpoint. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMedicines'] to see the possible values for this operation
     *
     * @throws \Mydex\ApiMrdSdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Mydex\ApiMrdSdk\Model\MedicineData[]|\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse|\Mydex\ApiMrdSdk\Model\AuthErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function searchMedicinesWithHttpInfo($x_mrd_scopes, $filters, $no_html = null, $nhs_links = null, $search_all = null, string $contentType = self::contentTypes['searchMedicines'][0])
    {
        $request = $this->searchMedicinesRequest($x_mrd_scopes, $filters, $no_html, $nhs_links, $search_all, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\MedicineData[]',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Mydex\ApiMrdSdk\Model\MedicineData[]',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\MedicineData[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\MedicinesErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Mydex\ApiMrdSdk\Model\AuthErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation searchMedicinesAsync
     *
     * Search Medicines content
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  \Mydex\ApiMrdSdk\Model\MedicinesSearchFilter[] $filters Structured Medicines search filters supplied using indexed bracket notation, for example filters[0][operator]&#x3D;LIKE&amp;filters[0][value]&#x3D;rapid acting insulin&amp;filters[0][condition]&#x3D;AND&amp;filters[1][operator]&#x3D;LIKE&amp;filters[1][value]&#x3D;diabetes&amp;filters[1][condition]&#x3D;. Each filter must contain exactly value, operator and condition. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string|null $search_all When supplied, the search also checks additional Medicines page content in addition to medicine descriptions. The only accepted value is &#39;true&#39;. This parameter is only valid on the search endpoint. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMedicines'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchMedicinesAsync($x_mrd_scopes, $filters, $no_html = null, $nhs_links = null, $search_all = null, string $contentType = self::contentTypes['searchMedicines'][0])
    {
        return $this->searchMedicinesAsyncWithHttpInfo($x_mrd_scopes, $filters, $no_html, $nhs_links, $search_all, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation searchMedicinesAsyncWithHttpInfo
     *
     * Search Medicines content
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  \Mydex\ApiMrdSdk\Model\MedicinesSearchFilter[] $filters Structured Medicines search filters supplied using indexed bracket notation, for example filters[0][operator]&#x3D;LIKE&amp;filters[0][value]&#x3D;rapid acting insulin&amp;filters[0][condition]&#x3D;AND&amp;filters[1][operator]&#x3D;LIKE&amp;filters[1][value]&#x3D;diabetes&amp;filters[1][condition]&#x3D;. Each filter must contain exactly value, operator and condition. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string|null $search_all When supplied, the search also checks additional Medicines page content in addition to medicine descriptions. The only accepted value is &#39;true&#39;. This parameter is only valid on the search endpoint. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMedicines'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function searchMedicinesAsyncWithHttpInfo($x_mrd_scopes, $filters, $no_html = null, $nhs_links = null, $search_all = null, string $contentType = self::contentTypes['searchMedicines'][0])
    {
        $returnType = '\Mydex\ApiMrdSdk\Model\MedicineData[]';
        $request = $this->searchMedicinesRequest($x_mrd_scopes, $filters, $no_html, $nhs_links, $search_all, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'searchMedicines'
     *
     * @param  string $x_mrd_scopes MRD service scope required for Medicines endpoints. (required)
     * @param  \Mydex\ApiMrdSdk\Model\MedicinesSearchFilter[] $filters Structured Medicines search filters supplied using indexed bracket notation, for example filters[0][operator]&#x3D;LIKE&amp;filters[0][value]&#x3D;rapid acting insulin&amp;filters[0][condition]&#x3D;AND&amp;filters[1][operator]&#x3D;LIKE&amp;filters[1][value]&#x3D;diabetes&amp;filters[1][condition]&#x3D;. Each filter must contain exactly value, operator and condition. (required)
     * @param  string|null $no_html When supplied, removes HTML markup from content text. The only accepted value is &#39;true&#39;. Omit the parameter to leave HTML unchanged. (optional)
     * @param  string|null $nhs_links When supplied, eligible MRD API links are replaced with their equivalent NHS website links. The only accepted value is &#39;true&#39;. Omit the parameter to leave links in their default form. (optional)
     * @param  string|null $search_all When supplied, the search also checks additional Medicines page content in addition to medicine descriptions. The only accepted value is &#39;true&#39;. This parameter is only valid on the search endpoint. (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['searchMedicines'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function searchMedicinesRequest($x_mrd_scopes, $filters, $no_html = null, $nhs_links = null, $search_all = null, string $contentType = self::contentTypes['searchMedicines'][0])
    {

        // verify the required parameter 'x_mrd_scopes' is set
        if ($x_mrd_scopes === null || (is_array($x_mrd_scopes) && count($x_mrd_scopes) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $x_mrd_scopes when calling searchMedicines'
            );
        }

        // verify the required parameter 'filters' is set
        if ($filters === null || (is_array($filters) && count($filters) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $filters when calling searchMedicines'
            );
        }
        if (count($filters) < 1) {
            throw new \InvalidArgumentException('invalid value for "$filters" when calling MedicinesApi.searchMedicines, number of items must be greater than or equal to 1.');
        }
        




        $resourcePath = '/medicines/search';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filters,
            'filters', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $no_html,
            'no_html', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $nhs_links,
            'nhs_links', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search_all,
            'search_all', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);

        // header params
        if ($x_mrd_scopes !== null) {
            $headerParams['X-Mrd-Scopes'] = ObjectSerializer::toHeaderValue($x_mrd_scopes);
        }



        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires OAuth (access token)
        if (!empty($this->config->getAccessToken())) {
            $headers['Authorization'] = 'Bearer ' . $this->config->getAccessToken();
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
