<?php
/**
 * ConditionPage
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MRD API
 *
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiMrdSdk\Model;

use \ArrayAccess;
use \Mydex\ApiMrdSdk\ObjectSerializer;

/**
 * ConditionPage Class Doc Comment
 *
 * @category Class
 * @description An NHS Conditions page stored and returned by MRD. The structure varies between source records and may contain nested health-topic content, webpage elements and videos.
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ConditionPage implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'ConditionPage';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'at_context' => 'string',
        'at_type' => 'string',
        'name' => 'string',
        'copyright_holder' => '\Mydex\ApiMrdSdk\Model\ConditionOrganisation',
        'license' => 'string',
        'author' => '\Mydex\ApiMrdSdk\Model\ConditionOrganisation',
        'about' => '\Mydex\ApiMrdSdk\Model\ConditionAbout',
        'description' => 'string',
        'url' => 'string',
        'genre' => 'string[]',
        'keywords' => '\Mydex\ApiMrdSdk\Model\ConditionKeywords',
        'date_modified' => '\DateTime',
        'last_reviewed' => '\DateTime[]',
        'breadcrumb' => '\Mydex\ApiMrdSdk\Model\ConditionBreadcrumb',
        'has_part' => '\Mydex\ApiMrdSdk\Model\ConditionHealthTopicContent[]',
        'related_link' => '\Mydex\ApiMrdSdk\Model\ConditionRelatedLink[]',
        'content_sub_types' => 'string[]',
        'headline' => 'string',
        'main_entity_of_page' => '\Mydex\ApiMrdSdk\Model\ConditionContentNode[]',
        'webpage' => 'string',
        'id' => 'int',
        'route_mapping' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'at_context' => null,
        'at_type' => null,
        'name' => null,
        'copyright_holder' => null,
        'license' => 'uri',
        'author' => null,
        'about' => null,
        'description' => null,
        'url' => 'uri',
        'genre' => null,
        'keywords' => null,
        'date_modified' => 'date-time',
        'last_reviewed' => 'date-time',
        'breadcrumb' => null,
        'has_part' => null,
        'related_link' => null,
        'content_sub_types' => null,
        'headline' => null,
        'main_entity_of_page' => null,
        'webpage' => 'uri',
        'id' => 'int64',
        'route_mapping' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'at_context' => false,
        'at_type' => false,
        'name' => false,
        'copyright_holder' => false,
        'license' => true,
        'author' => false,
        'about' => false,
        'description' => false,
        'url' => false,
        'genre' => false,
        'keywords' => false,
        'date_modified' => true,
        'last_reviewed' => false,
        'breadcrumb' => false,
        'has_part' => false,
        'related_link' => false,
        'content_sub_types' => false,
        'headline' => true,
        'main_entity_of_page' => false,
        'webpage' => false,
        'id' => false,
        'route_mapping' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'at_context' => '@context',
        'at_type' => '@type',
        'name' => 'name',
        'copyright_holder' => 'copyrightHolder',
        'license' => 'license',
        'author' => 'author',
        'about' => 'about',
        'description' => 'description',
        'url' => 'url',
        'genre' => 'genre',
        'keywords' => 'keywords',
        'date_modified' => 'dateModified',
        'last_reviewed' => 'lastReviewed',
        'breadcrumb' => 'breadcrumb',
        'has_part' => 'hasPart',
        'related_link' => 'relatedLink',
        'content_sub_types' => 'contentSubTypes',
        'headline' => 'headline',
        'main_entity_of_page' => 'mainEntityOfPage',
        'webpage' => 'webpage',
        'id' => 'id',
        'route_mapping' => 'route_mapping'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'at_context' => 'setAtContext',
        'at_type' => 'setAtType',
        'name' => 'setName',
        'copyright_holder' => 'setCopyrightHolder',
        'license' => 'setLicense',
        'author' => 'setAuthor',
        'about' => 'setAbout',
        'description' => 'setDescription',
        'url' => 'setUrl',
        'genre' => 'setGenre',
        'keywords' => 'setKeywords',
        'date_modified' => 'setDateModified',
        'last_reviewed' => 'setLastReviewed',
        'breadcrumb' => 'setBreadcrumb',
        'has_part' => 'setHasPart',
        'related_link' => 'setRelatedLink',
        'content_sub_types' => 'setContentSubTypes',
        'headline' => 'setHeadline',
        'main_entity_of_page' => 'setMainEntityOfPage',
        'webpage' => 'setWebpage',
        'id' => 'setId',
        'route_mapping' => 'setRouteMapping'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'at_context' => 'getAtContext',
        'at_type' => 'getAtType',
        'name' => 'getName',
        'copyright_holder' => 'getCopyrightHolder',
        'license' => 'getLicense',
        'author' => 'getAuthor',
        'about' => 'getAbout',
        'description' => 'getDescription',
        'url' => 'getUrl',
        'genre' => 'getGenre',
        'keywords' => 'getKeywords',
        'date_modified' => 'getDateModified',
        'last_reviewed' => 'getLastReviewed',
        'breadcrumb' => 'getBreadcrumb',
        'has_part' => 'getHasPart',
        'related_link' => 'getRelatedLink',
        'content_sub_types' => 'getContentSubTypes',
        'headline' => 'getHeadline',
        'main_entity_of_page' => 'getMainEntityOfPage',
        'webpage' => 'getWebpage',
        'id' => 'getId',
        'route_mapping' => 'getRouteMapping'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const AT_TYPE_MEDICAL_WEB_PAGE = 'MedicalWebPage';
    public const AT_TYPE_WEB_PAGE = 'WebPage';
    public const AT_TYPE_UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAtTypeAllowableValues()
    {
        return [
            self::AT_TYPE_MEDICAL_WEB_PAGE,
            self::AT_TYPE_WEB_PAGE,
            self::AT_TYPE_UNKNOWN_DEFAULT_OPEN_API,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('at_context', $data ?? [], null);
        $this->setIfExists('at_type', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('copyright_holder', $data ?? [], null);
        $this->setIfExists('license', $data ?? [], null);
        $this->setIfExists('author', $data ?? [], null);
        $this->setIfExists('about', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('genre', $data ?? [], null);
        $this->setIfExists('keywords', $data ?? [], null);
        $this->setIfExists('date_modified', $data ?? [], null);
        $this->setIfExists('last_reviewed', $data ?? [], null);
        $this->setIfExists('breadcrumb', $data ?? [], null);
        $this->setIfExists('has_part', $data ?? [], null);
        $this->setIfExists('related_link', $data ?? [], null);
        $this->setIfExists('content_sub_types', $data ?? [], null);
        $this->setIfExists('headline', $data ?? [], null);
        $this->setIfExists('main_entity_of_page', $data ?? [], null);
        $this->setIfExists('webpage', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('route_mapping', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['at_context'] === null) {
            $invalidProperties[] = "'at_context' can't be null";
        }
        if ($this->container['at_type'] === null) {
            $invalidProperties[] = "'at_type' can't be null";
        }
        $allowedValues = $this->getAtTypeAllowableValues();
        if (!is_null($this->container['at_type']) && !in_array($this->container['at_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'at_type', must be one of '%s'",
                $this->container['at_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['description'] === null) {
            $invalidProperties[] = "'description' can't be null";
        }
        if ($this->container['url'] === null) {
            $invalidProperties[] = "'url' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['route_mapping'] === null) {
            $invalidProperties[] = "'route_mapping' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets at_context
     *
     * @return string
     */
    public function getAtContext()
    {
        return $this->container['at_context'];
    }

    /**
     * Sets at_context
     *
     * @param string $at_context at_context
     *
     * @return self
     */
    public function setAtContext($at_context)
    {
        if (is_null($at_context)) {
            throw new \InvalidArgumentException('non-nullable at_context cannot be null');
        }
        $this->container['at_context'] = $at_context;

        return $this;
    }

    /**
     * Gets at_type
     *
     * @return string
     */
    public function getAtType()
    {
        return $this->container['at_type'];
    }

    /**
     * Sets at_type
     *
     * @param string $at_type at_type
     *
     * @return self
     */
    public function setAtType($at_type)
    {
        if (is_null($at_type)) {
            throw new \InvalidArgumentException('non-nullable at_type cannot be null');
        }
        $allowedValues = $this->getAtTypeAllowableValues();
        if (!in_array($at_type, $allowedValues, true)) {
            $at_type = self::AT_TYPE_UNKNOWN_DEFAULT_OPEN_API;
        }
        $this->container['at_type'] = $at_type;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets copyright_holder
     *
     * @return \Mydex\ApiMrdSdk\Model\ConditionOrganisation|null
     */
    public function getCopyrightHolder()
    {
        return $this->container['copyright_holder'];
    }

    /**
     * Sets copyright_holder
     *
     * @param \Mydex\ApiMrdSdk\Model\ConditionOrganisation|null $copyright_holder copyright_holder
     *
     * @return self
     */
    public function setCopyrightHolder($copyright_holder)
    {
        if (is_null($copyright_holder)) {
            throw new \InvalidArgumentException('non-nullable copyright_holder cannot be null');
        }
        $this->container['copyright_holder'] = $copyright_holder;

        return $this;
    }

    /**
     * Gets license
     *
     * @return string|null
     */
    public function getLicense()
    {
        return $this->container['license'];
    }

    /**
     * Sets license
     *
     * @param string|null $license license
     *
     * @return self
     */
    public function setLicense($license)
    {
        if (is_null($license)) {
            array_push($this->openAPINullablesSetToNull, 'license');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('license', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['license'] = $license;

        return $this;
    }

    /**
     * Gets author
     *
     * @return \Mydex\ApiMrdSdk\Model\ConditionOrganisation|null
     */
    public function getAuthor()
    {
        return $this->container['author'];
    }

    /**
     * Sets author
     *
     * @param \Mydex\ApiMrdSdk\Model\ConditionOrganisation|null $author author
     *
     * @return self
     */
    public function setAuthor($author)
    {
        if (is_null($author)) {
            throw new \InvalidArgumentException('non-nullable author cannot be null');
        }
        $this->container['author'] = $author;

        return $this;
    }

    /**
     * Gets about
     *
     * @return \Mydex\ApiMrdSdk\Model\ConditionAbout|null
     */
    public function getAbout()
    {
        return $this->container['about'];
    }

    /**
     * Sets about
     *
     * @param \Mydex\ApiMrdSdk\Model\ConditionAbout|null $about about
     *
     * @return self
     */
    public function setAbout($about)
    {
        if (is_null($about)) {
            throw new \InvalidArgumentException('non-nullable about cannot be null');
        }
        $this->container['about'] = $about;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            throw new \InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string $url MRD URL by default or the original NHS URL when nhs_links is enabled.
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            throw new \InvalidArgumentException('non-nullable url cannot be null');
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets genre
     *
     * @return string[]|null
     */
    public function getGenre()
    {
        return $this->container['genre'];
    }

    /**
     * Sets genre
     *
     * @param string[]|null $genre genre
     *
     * @return self
     */
    public function setGenre($genre)
    {
        if (is_null($genre)) {
            throw new \InvalidArgumentException('non-nullable genre cannot be null');
        }
        $this->container['genre'] = $genre;

        return $this;
    }

    /**
     * Gets keywords
     *
     * @return \Mydex\ApiMrdSdk\Model\ConditionKeywords|null
     */
    public function getKeywords()
    {
        return $this->container['keywords'];
    }

    /**
     * Sets keywords
     *
     * @param \Mydex\ApiMrdSdk\Model\ConditionKeywords|null $keywords keywords
     *
     * @return self
     */
    public function setKeywords($keywords)
    {
        if (is_null($keywords)) {
            throw new \InvalidArgumentException('non-nullable keywords cannot be null');
        }
        $this->container['keywords'] = $keywords;

        return $this;
    }

    /**
     * Gets date_modified
     *
     * @return \DateTime|null
     */
    public function getDateModified()
    {
        return $this->container['date_modified'];
    }

    /**
     * Sets date_modified
     *
     * @param \DateTime|null $date_modified date_modified
     *
     * @return self
     */
    public function setDateModified($date_modified)
    {
        if (is_null($date_modified)) {
            array_push($this->openAPINullablesSetToNull, 'date_modified');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_modified', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_modified'] = $date_modified;

        return $this;
    }

    /**
     * Gets last_reviewed
     *
     * @return \DateTime[]|null
     */
    public function getLastReviewed()
    {
        return $this->container['last_reviewed'];
    }

    /**
     * Sets last_reviewed
     *
     * @param \DateTime[]|null $last_reviewed The last review date followed by the next review-due date when supplied.
     *
     * @return self
     */
    public function setLastReviewed($last_reviewed)
    {
        if (is_null($last_reviewed)) {
            throw new \InvalidArgumentException('non-nullable last_reviewed cannot be null');
        }
        $this->container['last_reviewed'] = $last_reviewed;

        return $this;
    }

    /**
     * Gets breadcrumb
     *
     * @return \Mydex\ApiMrdSdk\Model\ConditionBreadcrumb|null
     */
    public function getBreadcrumb()
    {
        return $this->container['breadcrumb'];
    }

    /**
     * Sets breadcrumb
     *
     * @param \Mydex\ApiMrdSdk\Model\ConditionBreadcrumb|null $breadcrumb breadcrumb
     *
     * @return self
     */
    public function setBreadcrumb($breadcrumb)
    {
        if (is_null($breadcrumb)) {
            throw new \InvalidArgumentException('non-nullable breadcrumb cannot be null');
        }
        $this->container['breadcrumb'] = $breadcrumb;

        return $this;
    }

    /**
     * Gets has_part
     *
     * @return \Mydex\ApiMrdSdk\Model\ConditionHealthTopicContent[]|null
     */
    public function getHasPart()
    {
        return $this->container['has_part'];
    }

    /**
     * Sets has_part
     *
     * @param \Mydex\ApiMrdSdk\Model\ConditionHealthTopicContent[]|null $has_part has_part
     *
     * @return self
     */
    public function setHasPart($has_part)
    {
        if (is_null($has_part)) {
            throw new \InvalidArgumentException('non-nullable has_part cannot be null');
        }
        $this->container['has_part'] = $has_part;

        return $this;
    }

    /**
     * Gets related_link
     *
     * @return \Mydex\ApiMrdSdk\Model\ConditionRelatedLink[]|null
     */
    public function getRelatedLink()
    {
        return $this->container['related_link'];
    }

    /**
     * Sets related_link
     *
     * @param \Mydex\ApiMrdSdk\Model\ConditionRelatedLink[]|null $related_link related_link
     *
     * @return self
     */
    public function setRelatedLink($related_link)
    {
        if (is_null($related_link)) {
            throw new \InvalidArgumentException('non-nullable related_link cannot be null');
        }
        $this->container['related_link'] = $related_link;

        return $this;
    }

    /**
     * Gets content_sub_types
     *
     * @return string[]|null
     */
    public function getContentSubTypes()
    {
        return $this->container['content_sub_types'];
    }

    /**
     * Sets content_sub_types
     *
     * @param string[]|null $content_sub_types content_sub_types
     *
     * @return self
     */
    public function setContentSubTypes($content_sub_types)
    {
        if (is_null($content_sub_types)) {
            throw new \InvalidArgumentException('non-nullable content_sub_types cannot be null');
        }
        $this->container['content_sub_types'] = $content_sub_types;

        return $this;
    }

    /**
     * Gets headline
     *
     * @return string|null
     */
    public function getHeadline()
    {
        return $this->container['headline'];
    }

    /**
     * Sets headline
     *
     * @param string|null $headline headline
     *
     * @return self
     */
    public function setHeadline($headline)
    {
        if (is_null($headline)) {
            array_push($this->openAPINullablesSetToNull, 'headline');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('headline', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['headline'] = $headline;

        return $this;
    }

    /**
     * Gets main_entity_of_page
     *
     * @return \Mydex\ApiMrdSdk\Model\ConditionContentNode[]|null
     */
    public function getMainEntityOfPage()
    {
        return $this->container['main_entity_of_page'];
    }

    /**
     * Sets main_entity_of_page
     *
     * @param \Mydex\ApiMrdSdk\Model\ConditionContentNode[]|null $main_entity_of_page main_entity_of_page
     *
     * @return self
     */
    public function setMainEntityOfPage($main_entity_of_page)
    {
        if (is_null($main_entity_of_page)) {
            throw new \InvalidArgumentException('non-nullable main_entity_of_page cannot be null');
        }
        $this->container['main_entity_of_page'] = $main_entity_of_page;

        return $this;
    }

    /**
     * Gets webpage
     *
     * @return string|null
     */
    public function getWebpage()
    {
        return $this->container['webpage'];
    }

    /**
     * Sets webpage
     *
     * @param string|null $webpage webpage
     *
     * @return self
     */
    public function setWebpage($webpage)
    {
        if (is_null($webpage)) {
            throw new \InvalidArgumentException('non-nullable webpage cannot be null');
        }
        $this->container['webpage'] = $webpage;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets route_mapping
     *
     * @return string
     */
    public function getRouteMapping()
    {
        return $this->container['route_mapping'];
    }

    /**
     * Sets route_mapping
     *
     * @param string $route_mapping route_mapping
     *
     * @return self
     */
    public function setRouteMapping($route_mapping)
    {
        if (is_null($route_mapping)) {
            throw new \InvalidArgumentException('non-nullable route_mapping cannot be null');
        }
        $this->container['route_mapping'] = $route_mapping;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


