<?php
/**
 * LivewellContentElementMainEntityInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MRD API
 *
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiMrdSdk\Model;

use \ArrayAccess;
use \Mydex\ApiMrdSdk\ObjectSerializer;

/**
 * LivewellContentElementMainEntityInner Class Doc Comment
 *
 * @category Class
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class LivewellContentElementMainEntityInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'LivewellContentElement_mainEntity_inner';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'at_type' => 'string',
        'name' => 'string',
        'identifier' => '\Mydex\ApiMrdSdk\Model\ConditionVideoObjectIdentifier',
        'position' => 'int',
        'headline' => 'string',
        'description' => 'string',
        'url' => 'string',
        'text' => 'string',
        'links' => '\Mydex\ApiMrdSdk\Model\LivewellAnswerLinksInner[]',
        'accepted_answer' => '\Mydex\ApiMrdSdk\Model\LivewellAnswer',
        'main_entity' => '\Mydex\ApiMrdSdk\Model\LivewellContentElementMainEntityInner[]',
        'main_entity_of_page' => '\Mydex\ApiMrdSdk\Model\LivewellContentElementMainEntityInner[]',
        'has_part' => '\Mydex\ApiMrdSdk\Model\LivewellContentElementMainEntityInner[]',
        'embed_url' => 'string',
        'content_url' => 'string',
        'duration' => 'string',
        'alternate_name' => 'string',
        'upload_date' => '\DateTime',
        'last_reviewed' => 'string[]',
        'thumbnail_url' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'at_type' => null,
        'name' => null,
        'identifier' => null,
        'position' => null,
        'headline' => null,
        'description' => null,
        'url' => 'uri',
        'text' => null,
        'links' => null,
        'accepted_answer' => null,
        'main_entity' => null,
        'main_entity_of_page' => null,
        'has_part' => null,
        'embed_url' => null,
        'content_url' => null,
        'duration' => null,
        'alternate_name' => null,
        'upload_date' => 'date-time',
        'last_reviewed' => null,
        'thumbnail_url' => 'uri'
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'at_type' => false,
        'name' => true,
        'identifier' => true,
        'position' => true,
        'headline' => true,
        'description' => true,
        'url' => true,
        'text' => true,
        'links' => false,
        'accepted_answer' => true,
        'main_entity' => false,
        'main_entity_of_page' => false,
        'has_part' => false,
        'embed_url' => true,
        'content_url' => true,
        'duration' => true,
        'alternate_name' => true,
        'upload_date' => true,
        'last_reviewed' => true,
        'thumbnail_url' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'at_type' => '@type',
        'name' => 'name',
        'identifier' => 'identifier',
        'position' => 'position',
        'headline' => 'headline',
        'description' => 'description',
        'url' => 'url',
        'text' => 'text',
        'links' => 'links',
        'accepted_answer' => 'acceptedAnswer',
        'main_entity' => 'mainEntity',
        'main_entity_of_page' => 'mainEntityOfPage',
        'has_part' => 'hasPart',
        'embed_url' => 'embedUrl',
        'content_url' => 'contentUrl',
        'duration' => 'duration',
        'alternate_name' => 'alternateName',
        'upload_date' => 'uploadDate',
        'last_reviewed' => 'lastReviewed',
        'thumbnail_url' => 'thumbnailUrl'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'at_type' => 'setAtType',
        'name' => 'setName',
        'identifier' => 'setIdentifier',
        'position' => 'setPosition',
        'headline' => 'setHeadline',
        'description' => 'setDescription',
        'url' => 'setUrl',
        'text' => 'setText',
        'links' => 'setLinks',
        'accepted_answer' => 'setAcceptedAnswer',
        'main_entity' => 'setMainEntity',
        'main_entity_of_page' => 'setMainEntityOfPage',
        'has_part' => 'setHasPart',
        'embed_url' => 'setEmbedUrl',
        'content_url' => 'setContentUrl',
        'duration' => 'setDuration',
        'alternate_name' => 'setAlternateName',
        'upload_date' => 'setUploadDate',
        'last_reviewed' => 'setLastReviewed',
        'thumbnail_url' => 'setThumbnailUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'at_type' => 'getAtType',
        'name' => 'getName',
        'identifier' => 'getIdentifier',
        'position' => 'getPosition',
        'headline' => 'getHeadline',
        'description' => 'getDescription',
        'url' => 'getUrl',
        'text' => 'getText',
        'links' => 'getLinks',
        'accepted_answer' => 'getAcceptedAnswer',
        'main_entity' => 'getMainEntity',
        'main_entity_of_page' => 'getMainEntityOfPage',
        'has_part' => 'getHasPart',
        'embed_url' => 'getEmbedUrl',
        'content_url' => 'getContentUrl',
        'duration' => 'getDuration',
        'alternate_name' => 'getAlternateName',
        'upload_date' => 'getUploadDate',
        'last_reviewed' => 'getLastReviewed',
        'thumbnail_url' => 'getThumbnailUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('at_type', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('identifier', $data ?? [], null);
        $this->setIfExists('position', $data ?? [], null);
        $this->setIfExists('headline', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('url', $data ?? [], null);
        $this->setIfExists('text', $data ?? [], null);
        $this->setIfExists('links', $data ?? [], null);
        $this->setIfExists('accepted_answer', $data ?? [], null);
        $this->setIfExists('main_entity', $data ?? [], null);
        $this->setIfExists('main_entity_of_page', $data ?? [], null);
        $this->setIfExists('has_part', $data ?? [], null);
        $this->setIfExists('embed_url', $data ?? [], null);
        $this->setIfExists('content_url', $data ?? [], null);
        $this->setIfExists('duration', $data ?? [], null);
        $this->setIfExists('alternate_name', $data ?? [], null);
        $this->setIfExists('upload_date', $data ?? [], null);
        $this->setIfExists('last_reviewed', $data ?? [], null);
        $this->setIfExists('thumbnail_url', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['position']) && ($this->container['position'] < 0)) {
            $invalidProperties[] = "invalid value for 'position', must be bigger than or equal to 0.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets at_type
     *
     * @return string|null
     */
    public function getAtType()
    {
        return $this->container['at_type'];
    }

    /**
     * Sets at_type
     *
     * @param string|null $at_type at_type
     *
     * @return self
     */
    public function setAtType($at_type)
    {
        if (is_null($at_type)) {
            throw new \InvalidArgumentException('non-nullable at_type cannot be null');
        }
        $this->container['at_type'] = $at_type;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets identifier
     *
     * @return \Mydex\ApiMrdSdk\Model\ConditionVideoObjectIdentifier|null
     */
    public function getIdentifier()
    {
        return $this->container['identifier'];
    }

    /**
     * Sets identifier
     *
     * @param \Mydex\ApiMrdSdk\Model\ConditionVideoObjectIdentifier|null $identifier identifier
     *
     * @return self
     */
    public function setIdentifier($identifier)
    {
        if (is_null($identifier)) {
            array_push($this->openAPINullablesSetToNull, 'identifier');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('identifier', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['identifier'] = $identifier;

        return $this;
    }

    /**
     * Gets position
     *
     * @return int|null
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     *
     * @param int|null $position position
     *
     * @return self
     */
    public function setPosition($position)
    {
        if (is_null($position)) {
            array_push($this->openAPINullablesSetToNull, 'position');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('position', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($position) && ($position < 0)) {
            throw new \InvalidArgumentException('invalid value for $position when calling LivewellContentElementMainEntityInner., must be bigger than or equal to 0.');
        }

        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets headline
     *
     * @return string|null
     */
    public function getHeadline()
    {
        return $this->container['headline'];
    }

    /**
     * Sets headline
     *
     * @param string|null $headline headline
     *
     * @return self
     */
    public function setHeadline($headline)
    {
        if (is_null($headline)) {
            array_push($this->openAPINullablesSetToNull, 'headline');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('headline', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['headline'] = $headline;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets url
     *
     * @return string|null
     */
    public function getUrl()
    {
        return $this->container['url'];
    }

    /**
     * Sets url
     *
     * @param string|null $url url
     *
     * @return self
     */
    public function setUrl($url)
    {
        if (is_null($url)) {
            array_push($this->openAPINullablesSetToNull, 'url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['url'] = $url;

        return $this;
    }

    /**
     * Gets text
     *
     * @return string|null
     */
    public function getText()
    {
        return $this->container['text'];
    }

    /**
     * Sets text
     *
     * @param string|null $text Rendered video HTML or processed plain text.
     *
     * @return self
     */
    public function setText($text)
    {
        if (is_null($text)) {
            array_push($this->openAPINullablesSetToNull, 'text');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('text', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['text'] = $text;

        return $this;
    }

    /**
     * Gets links
     *
     * @return \Mydex\ApiMrdSdk\Model\LivewellAnswerLinksInner[]|null
     */
    public function getLinks()
    {
        return $this->container['links'];
    }

    /**
     * Sets links
     *
     * @param \Mydex\ApiMrdSdk\Model\LivewellAnswerLinksInner[]|null $links links
     *
     * @return self
     */
    public function setLinks($links)
    {
        if (is_null($links)) {
            throw new \InvalidArgumentException('non-nullable links cannot be null');
        }
        $this->container['links'] = $links;

        return $this;
    }

    /**
     * Gets accepted_answer
     *
     * @return \Mydex\ApiMrdSdk\Model\LivewellAnswer|null
     */
    public function getAcceptedAnswer()
    {
        return $this->container['accepted_answer'];
    }

    /**
     * Sets accepted_answer
     *
     * @param \Mydex\ApiMrdSdk\Model\LivewellAnswer|null $accepted_answer accepted_answer
     *
     * @return self
     */
    public function setAcceptedAnswer($accepted_answer)
    {
        if (is_null($accepted_answer)) {
            array_push($this->openAPINullablesSetToNull, 'accepted_answer');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('accepted_answer', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['accepted_answer'] = $accepted_answer;

        return $this;
    }

    /**
     * Gets main_entity
     *
     * @return \Mydex\ApiMrdSdk\Model\LivewellContentElementMainEntityInner[]|null
     */
    public function getMainEntity()
    {
        return $this->container['main_entity'];
    }

    /**
     * Sets main_entity
     *
     * @param \Mydex\ApiMrdSdk\Model\LivewellContentElementMainEntityInner[]|null $main_entity main_entity
     *
     * @return self
     */
    public function setMainEntity($main_entity)
    {
        if (is_null($main_entity)) {
            throw new \InvalidArgumentException('non-nullable main_entity cannot be null');
        }
        $this->container['main_entity'] = $main_entity;

        return $this;
    }

    /**
     * Gets main_entity_of_page
     *
     * @return \Mydex\ApiMrdSdk\Model\LivewellContentElementMainEntityInner[]|null
     */
    public function getMainEntityOfPage()
    {
        return $this->container['main_entity_of_page'];
    }

    /**
     * Sets main_entity_of_page
     *
     * @param \Mydex\ApiMrdSdk\Model\LivewellContentElementMainEntityInner[]|null $main_entity_of_page main_entity_of_page
     *
     * @return self
     */
    public function setMainEntityOfPage($main_entity_of_page)
    {
        if (is_null($main_entity_of_page)) {
            throw new \InvalidArgumentException('non-nullable main_entity_of_page cannot be null');
        }
        $this->container['main_entity_of_page'] = $main_entity_of_page;

        return $this;
    }

    /**
     * Gets has_part
     *
     * @return \Mydex\ApiMrdSdk\Model\LivewellContentElementMainEntityInner[]|null
     */
    public function getHasPart()
    {
        return $this->container['has_part'];
    }

    /**
     * Sets has_part
     *
     * @param \Mydex\ApiMrdSdk\Model\LivewellContentElementMainEntityInner[]|null $has_part has_part
     *
     * @return self
     */
    public function setHasPart($has_part)
    {
        if (is_null($has_part)) {
            throw new \InvalidArgumentException('non-nullable has_part cannot be null');
        }
        $this->container['has_part'] = $has_part;

        return $this;
    }

    /**
     * Gets embed_url
     *
     * @return string|null
     */
    public function getEmbedUrl()
    {
        return $this->container['embed_url'];
    }

    /**
     * Sets embed_url
     *
     * @param string|null $embed_url embed_url
     *
     * @return self
     */
    public function setEmbedUrl($embed_url)
    {
        if (is_null($embed_url)) {
            array_push($this->openAPINullablesSetToNull, 'embed_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('embed_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['embed_url'] = $embed_url;

        return $this;
    }

    /**
     * Gets content_url
     *
     * @return string|null
     */
    public function getContentUrl()
    {
        return $this->container['content_url'];
    }

    /**
     * Sets content_url
     *
     * @param string|null $content_url content_url
     *
     * @return self
     */
    public function setContentUrl($content_url)
    {
        if (is_null($content_url)) {
            array_push($this->openAPINullablesSetToNull, 'content_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('content_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['content_url'] = $content_url;

        return $this;
    }

    /**
     * Gets duration
     *
     * @return string|null
     */
    public function getDuration()
    {
        return $this->container['duration'];
    }

    /**
     * Sets duration
     *
     * @param string|null $duration duration
     *
     * @return self
     */
    public function setDuration($duration)
    {
        if (is_null($duration)) {
            array_push($this->openAPINullablesSetToNull, 'duration');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('duration', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['duration'] = $duration;

        return $this;
    }

    /**
     * Gets alternate_name
     *
     * @return string|null
     */
    public function getAlternateName()
    {
        return $this->container['alternate_name'];
    }

    /**
     * Sets alternate_name
     *
     * @param string|null $alternate_name alternate_name
     *
     * @return self
     */
    public function setAlternateName($alternate_name)
    {
        if (is_null($alternate_name)) {
            array_push($this->openAPINullablesSetToNull, 'alternate_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('alternate_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['alternate_name'] = $alternate_name;

        return $this;
    }

    /**
     * Gets upload_date
     *
     * @return \DateTime|null
     */
    public function getUploadDate()
    {
        return $this->container['upload_date'];
    }

    /**
     * Sets upload_date
     *
     * @param \DateTime|null $upload_date upload_date
     *
     * @return self
     */
    public function setUploadDate($upload_date)
    {
        if (is_null($upload_date)) {
            array_push($this->openAPINullablesSetToNull, 'upload_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('upload_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['upload_date'] = $upload_date;

        return $this;
    }

    /**
     * Gets last_reviewed
     *
     * @return string[]|null
     */
    public function getLastReviewed()
    {
        return $this->container['last_reviewed'];
    }

    /**
     * Sets last_reviewed
     *
     * @param string[]|null $last_reviewed last_reviewed
     *
     * @return self
     */
    public function setLastReviewed($last_reviewed)
    {
        if (is_null($last_reviewed)) {
            array_push($this->openAPINullablesSetToNull, 'last_reviewed');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_reviewed', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_reviewed'] = $last_reviewed;

        return $this;
    }

    /**
     * Gets thumbnail_url
     *
     * @return string|null
     */
    public function getThumbnailUrl()
    {
        return $this->container['thumbnail_url'];
    }

    /**
     * Sets thumbnail_url
     *
     * @param string|null $thumbnail_url thumbnail_url
     *
     * @return self
     */
    public function setThumbnailUrl($thumbnail_url)
    {
        if (is_null($thumbnail_url)) {
            array_push($this->openAPINullablesSetToNull, 'thumbnail_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('thumbnail_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['thumbnail_url'] = $thumbnail_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


