<?php
/**
 * MdsAllField
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MRD API
 *
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiMrdSdk\Model;

use \ArrayAccess;
use \Mydex\ApiMrdSdk\ObjectSerializer;

/**
 * MdsAllField Class Doc Comment
 *
 * @category Class
 * @description Extended field information returned by the all-datasets-and-fields endpoint.
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MdsAllField implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MdsAllField';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'field_name' => 'string',
        'display_name' => 'string',
        'data_type' => 'string',
        'field_description' => 'string',
        'field_example' => 'mixed',
        'source' => 'string',
        'field_order' => 'mixed',
        'length' => 'mixed',
        'not_null' => 'mixed',
        'default' => 'mixed'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'field_name' => null,
        'display_name' => null,
        'data_type' => null,
        'field_description' => null,
        'field_example' => null,
        'source' => null,
        'field_order' => null,
        'length' => null,
        'not_null' => null,
        'default' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'field_name' => false,
        'display_name' => true,
        'data_type' => true,
        'field_description' => true,
        'field_example' => true,
        'source' => true,
        'field_order' => true,
        'length' => true,
        'not_null' => true,
        'default' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'field_name' => 'field_name',
        'display_name' => 'display_name',
        'data_type' => 'data_type',
        'field_description' => 'field_description',
        'field_example' => 'field_example',
        'source' => 'source',
        'field_order' => 'field_order',
        'length' => 'length',
        'not_null' => 'not_null',
        'default' => 'default'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'field_name' => 'setFieldName',
        'display_name' => 'setDisplayName',
        'data_type' => 'setDataType',
        'field_description' => 'setFieldDescription',
        'field_example' => 'setFieldExample',
        'source' => 'setSource',
        'field_order' => 'setFieldOrder',
        'length' => 'setLength',
        'not_null' => 'setNotNull',
        'default' => 'setDefault'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'field_name' => 'getFieldName',
        'display_name' => 'getDisplayName',
        'data_type' => 'getDataType',
        'field_description' => 'getFieldDescription',
        'field_example' => 'getFieldExample',
        'source' => 'getSource',
        'field_order' => 'getFieldOrder',
        'length' => 'getLength',
        'not_null' => 'getNotNull',
        'default' => 'getDefault'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('field_name', $data ?? [], null);
        $this->setIfExists('display_name', $data ?? [], null);
        $this->setIfExists('data_type', $data ?? [], null);
        $this->setIfExists('field_description', $data ?? [], null);
        $this->setIfExists('field_example', $data ?? [], null);
        $this->setIfExists('source', $data ?? [], null);
        $this->setIfExists('field_order', $data ?? [], null);
        $this->setIfExists('length', $data ?? [], null);
        $this->setIfExists('not_null', $data ?? [], null);
        $this->setIfExists('default', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['field_name'] === null) {
            $invalidProperties[] = "'field_name' can't be null";
        }
        if ($this->container['display_name'] === null && !$this->isNullableSetToNull('display_name')) {
            $invalidProperties[] = "'display_name' is required";
        }
        if ($this->container['data_type'] === null && !$this->isNullableSetToNull('data_type')) {
            $invalidProperties[] = "'data_type' is required";
        }
        if ($this->container['field_description'] === null && !$this->isNullableSetToNull('field_description')) {
            $invalidProperties[] = "'field_description' is required";
        }
        if ($this->container['field_example'] === null && !$this->isNullableSetToNull('field_example')) {
            $invalidProperties[] = "'field_example' is required";
        }
        if ($this->container['source'] === null && !$this->isNullableSetToNull('source')) {
            $invalidProperties[] = "'source' is required";
        }
        if ($this->container['field_order'] === null && !$this->isNullableSetToNull('field_order')) {
            $invalidProperties[] = "'field_order' is required";
        }
        if ($this->container['length'] === null && !$this->isNullableSetToNull('length')) {
            $invalidProperties[] = "'length' is required";
        }
        if ($this->container['not_null'] === null && !$this->isNullableSetToNull('not_null')) {
            $invalidProperties[] = "'not_null' is required";
        }
        if ($this->container['default'] === null && !$this->isNullableSetToNull('default')) {
            $invalidProperties[] = "'default' is required";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets field_name
     *
     * @return string
     */
    public function getFieldName()
    {
        return $this->container['field_name'];
    }

    /**
     * Sets field_name
     *
     * @param string $field_name field_name
     *
     * @return self
     */
    public function setFieldName($field_name)
    {
        if (is_null($field_name)) {
            throw new \InvalidArgumentException('non-nullable field_name cannot be null');
        }
        $this->container['field_name'] = $field_name;

        return $this;
    }

    /**
     * Gets display_name
     *
     * @return string|null
     */
    public function getDisplayName()
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     *
     * @param string|null $display_name display_name
     *
     * @return self
     */
    public function setDisplayName($display_name)
    {
        if (is_null($display_name)) {
            array_push($this->openAPINullablesSetToNull, 'display_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('display_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets data_type
     *
     * @return string|null
     */
    public function getDataType()
    {
        return $this->container['data_type'];
    }

    /**
     * Sets data_type
     *
     * @param string|null $data_type data_type
     *
     * @return self
     */
    public function setDataType($data_type)
    {
        if (is_null($data_type)) {
            array_push($this->openAPINullablesSetToNull, 'data_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('data_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['data_type'] = $data_type;

        return $this;
    }

    /**
     * Gets field_description
     *
     * @return string|null
     */
    public function getFieldDescription()
    {
        return $this->container['field_description'];
    }

    /**
     * Sets field_description
     *
     * @param string|null $field_description field_description
     *
     * @return self
     */
    public function setFieldDescription($field_description)
    {
        if (is_null($field_description)) {
            array_push($this->openAPINullablesSetToNull, 'field_description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('field_description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['field_description'] = $field_description;

        return $this;
    }

    /**
     * Gets field_example
     *
     * @return mixed|null
     */
    public function getFieldExample()
    {
        return $this->container['field_example'];
    }

    /**
     * Sets field_example
     *
     * @param mixed|null $field_example Example value associated with the field. The returned value type depends on the field definition.
     *
     * @return self
     */
    public function setFieldExample($field_example)
    {
        if (is_null($field_example)) {
            array_push($this->openAPINullablesSetToNull, 'field_example');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('field_example', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['field_example'] = $field_example;

        return $this;
    }

    /**
     * Gets source
     *
     * @return string|null
     */
    public function getSource()
    {
        return $this->container['source'];
    }

    /**
     * Sets source
     *
     * @param string|null $source Source associated with the MDS field.
     *
     * @return self
     */
    public function setSource($source)
    {
        if (is_null($source)) {
            array_push($this->openAPINullablesSetToNull, 'source');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('source', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['source'] = $source;

        return $this;
    }

    /**
     * Gets field_order
     *
     * @return mixed|null
     */
    public function getFieldOrder()
    {
        return $this->container['field_order'];
    }

    /**
     * Sets field_order
     *
     * @param mixed|null $field_order Field ordering value as returned by the underlying MDS database.
     *
     * @return self
     */
    public function setFieldOrder($field_order)
    {
        if (is_null($field_order)) {
            array_push($this->openAPINullablesSetToNull, 'field_order');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('field_order', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['field_order'] = $field_order;

        return $this;
    }

    /**
     * Gets length
     *
     * @return mixed|null
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param mixed|null $length Maximum field length when applicable, as returned by the underlying MDS database.
     *
     * @return self
     */
    public function setLength($length)
    {
        if (is_null($length)) {
            array_push($this->openAPINullablesSetToNull, 'length');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('length', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['length'] = $length;

        return $this;
    }

    /**
     * Gets not_null
     *
     * @return mixed|null
     */
    public function getNotNull()
    {
        return $this->container['not_null'];
    }

    /**
     * Sets not_null
     *
     * @param mixed|null $not_null Underlying not-null value returned directly from the MDS database.
     *
     * @return self
     */
    public function setNotNull($not_null)
    {
        if (is_null($not_null)) {
            array_push($this->openAPINullablesSetToNull, 'not_null');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('not_null', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['not_null'] = $not_null;

        return $this;
    }

    /**
     * Gets default
     *
     * @return mixed|null
     */
    public function getDefault()
    {
        return $this->container['default'];
    }

    /**
     * Sets default
     *
     * @param mixed|null $default Underlying default value returned directly from the MDS database.
     *
     * @return self
     */
    public function setDefault($default)
    {
        if (is_null($default)) {
            array_push($this->openAPINullablesSetToNull, 'default');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['default'] = $default;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


