<?php
/**
 * MeasurementType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MRD API
 *
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Mydex\ApiMrdSdk\Model;

use \ArrayAccess;
use \Mydex\ApiMrdSdk\ObjectSerializer;

/**
 * MeasurementType Class Doc Comment
 *
 * @category Class
 * @description Measurement definition including its group and unit.
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MeasurementType implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'MeasurementType';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'measurement_id' => 'string',
        'measurement_name' => 'string',
        'measurement_group' => 'string',
        'measurement_unit' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'measurement_id' => null,
        'measurement_name' => null,
        'measurement_group' => null,
        'measurement_unit' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'measurement_id' => false,
        'measurement_name' => false,
        'measurement_group' => false,
        'measurement_unit' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'measurement_id' => 'measurement_id',
        'measurement_name' => 'measurement_name',
        'measurement_group' => 'measurement_group',
        'measurement_unit' => 'measurement_unit'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'measurement_id' => 'setMeasurementId',
        'measurement_name' => 'setMeasurementName',
        'measurement_group' => 'setMeasurementGroup',
        'measurement_unit' => 'setMeasurementUnit'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'measurement_id' => 'getMeasurementId',
        'measurement_name' => 'getMeasurementName',
        'measurement_group' => 'getMeasurementGroup',
        'measurement_unit' => 'getMeasurementUnit'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('measurement_id', $data ?? [], null);
        $this->setIfExists('measurement_name', $data ?? [], null);
        $this->setIfExists('measurement_group', $data ?? [], null);
        $this->setIfExists('measurement_unit', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['measurement_id'] === null) {
            $invalidProperties[] = "'measurement_id' can't be null";
        }
        if ($this->container['measurement_name'] === null) {
            $invalidProperties[] = "'measurement_name' can't be null";
        }
        if ($this->container['measurement_group'] === null) {
            $invalidProperties[] = "'measurement_group' can't be null";
        }
        if ($this->container['measurement_unit'] === null) {
            $invalidProperties[] = "'measurement_unit' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets measurement_id
     *
     * @return string
     */
    public function getMeasurementId()
    {
        return $this->container['measurement_id'];
    }

    /**
     * Sets measurement_id
     *
     * @param string $measurement_id Measurement types.
     *
     * @return self
     */
    public function setMeasurementId($measurement_id)
    {
        if (is_null($measurement_id)) {
            throw new \InvalidArgumentException('non-nullable measurement_id cannot be null');
        }
        $this->container['measurement_id'] = $measurement_id;

        return $this;
    }

    /**
     * Gets measurement_name
     *
     * @return string
     */
    public function getMeasurementName()
    {
        return $this->container['measurement_name'];
    }

    /**
     * Sets measurement_name
     *
     * @param string $measurement_name measurement_name
     *
     * @return self
     */
    public function setMeasurementName($measurement_name)
    {
        if (is_null($measurement_name)) {
            throw new \InvalidArgumentException('non-nullable measurement_name cannot be null');
        }
        $this->container['measurement_name'] = $measurement_name;

        return $this;
    }

    /**
     * Gets measurement_group
     *
     * @return string
     */
    public function getMeasurementGroup()
    {
        return $this->container['measurement_group'];
    }

    /**
     * Sets measurement_group
     *
     * @param string $measurement_group measurement_group
     *
     * @return self
     */
    public function setMeasurementGroup($measurement_group)
    {
        if (is_null($measurement_group)) {
            throw new \InvalidArgumentException('non-nullable measurement_group cannot be null');
        }
        $this->container['measurement_group'] = $measurement_group;

        return $this;
    }

    /**
     * Gets measurement_unit
     *
     * @return string
     */
    public function getMeasurementUnit()
    {
        return $this->container['measurement_unit'];
    }

    /**
     * Sets measurement_unit
     *
     * @param string $measurement_unit measurement_unit
     *
     * @return self
     */
    public function setMeasurementUnit($measurement_unit)
    {
        if (is_null($measurement_unit)) {
            throw new \InvalidArgumentException('non-nullable measurement_unit cannot be null');
        }
        $this->container['measurement_unit'] = $measurement_unit;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


