<?php
/**
 * CountryIddTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MRD API
 *
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mydex\ApiMrdSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CountryIddTest Class Doc Comment
 *
 * @category    Class
 * @description International dialling information. If no dialling suffixes exist, the API returns an empty object.
 * @package     Mydex\ApiMrdSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CountryIddTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CountryIdd"
     */
    public function testCountryIdd()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "root"
     */
    public function testPropertyRoot()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "suffixes"
     */
    public function testPropertySuffixes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
