<?php
/**
 * PregnancyHealthTopicContentTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MRD API
 *
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mydex\ApiMrdSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PregnancyHealthTopicContentTest Class Doc Comment
 *
 * @category    Class
 * @description A structured health-topic section included within a Pregnancy page.
 * @package     Mydex\ApiMrdSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PregnancyHealthTopicContentTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PregnancyHealthTopicContent"
     */
    public function testPregnancyHealthTopicContent()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "at_type"
     */
    public function testPropertyAtType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "has_health_aspect"
     */
    public function testPropertyHasHealthAspect()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "headline"
     */
    public function testPropertyHeadline()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "has_part"
     */
    public function testPropertyHasPart()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
