<?php
/**
 * PregnancyVideoObjectTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Mydex\ApiMrdSdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MRD API
 *
 * API for retrieving Master Reference Data
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.23.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Mydex\ApiMrdSdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PregnancyVideoObjectTest Class Doc Comment
 *
 * @category    Class
 * @description Video content supplied by the NHS Pregnancy dataset. VideoObject entries are passed through without content formatting.
 * @package     Mydex\ApiMrdSdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PregnancyVideoObjectTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PregnancyVideoObject"
     */
    public function testPregnancyVideoObject()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "at_type"
     */
    public function testPropertyAtType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "thumbnail_url"
     */
    public function testPropertyThumbnailUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "upload_date"
     */
    public function testPropertyUploadDate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "content_url"
     */
    public function testPropertyContentUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "embed_url"
     */
    public function testPropertyEmbedUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
